"""Deterministic aggregation: group classified paragraphs by category.

No LLM, no estimation -- plain grouping and counting. This removes the
"roughly count mentions" instability from the old design entirely: counts
are computed in code from real classification labels, not generated by
the model as an estimate.
"""
from collections import defaultdict
from edgar_risk_screener.paragraph_classifier import ParagraphClassification

MAX_EXAMPLE_PARAGRAPHS = 3  # cap for readability, not a trust signal


def group_paragraphs_by_category(
    paragraphs: list[str],
    classifications: list[ParagraphClassification],
) -> dict[str, list[str]]:
    """Return {category_name: [paragraph_text, ...]}, one entry per
    category that appeared at least once. A category's mention count is
    len(its paragraph list) -- no separate counting step needed.
    """
    if len(paragraphs) != len(classifications):
        raise ValueError(
            f"paragraphs ({len(paragraphs)}) and classifications ({len(classifications)}) "
            "must be the same length and in the same order"
        )

    grouped: dict[str, list[str]] = defaultdict(list)
    for paragraph, classification in zip(paragraphs, classifications):
        grouped[classification.category].append(paragraph)

    return dict(grouped)


def mention_counts(grouped: dict[str, list[str]]) -> dict[str, int]:
    return {category: len(paras) for category, paras in grouped.items()}
